name: questbook
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # cloud_firestore: ^0.13.7
  cloud_firestore: ^0.16.0

  # firebase_database: ^3.1.6
  firebase_database: ^6.0.0

  # firebase_auth: ^0.16.1
  firebase_auth: ^0.20.0+1

  # google_sign_in: ^4.5.1
  google_sign_in: ^4.5.9

  path_provider: ^1.3.0
  in_app_purchase: ^0.3.4+3
  loop_page_view: ^1.0.9
  audioplayers: ^0.16.1

  # firebase_core: ^0.4.4
  firebase_core: ^0.7.0
  
  card_selector: ^0.1.0
  flutter_stack_card: ^0.2.0+1
  url_launcher: ^5.7.2
  provider: ^4.3.2

  # firebase_admob: ^0.9.3
  firebase_admob: ^0.11.0

  animated_button: ^0.1.2
  rxdart: ^0.24.1
  http: ^0.12.1
  flutter_local_notifications: ^3.0.1+2
  circular_countdown: ^1.2.1
  custom_timer: ^0.0.2
  flare_flutter: ^2.0.6
  flutter_launcher_icons: ^0.7.4
  liquid_progress_indicator: ^0.3.2
  firebase_analytics: ^5.0.11

  # firebase_crashlytics: ^0.1.4+1
  firebase_crashlytics: ^0.4.0+1
  
  



  

 

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
   android: "launcher_icon"
   ios: true
   image_path: "assets/лого.jpg"
 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/abs.png
    - assets/clover.png
    - assets/time.png
    - assets/setings.png
    - assets/key.png
    - assets/insta.png
    - assets/diamondsMidle.png
    - assets/diamondsLitle.png
    - assets/diamondsBig.png
    - assets/ezgif.com-gif-maker.gif
    - assets/old-grunge-paper-texture-background (1).png
    - assets/Ключ•2.png
    - assets/Ключ•3.png
    - assets/Мини-игра.png
    - assets/кольцо.png
    - assets/корона.png
    - assets/леденец.png
    - assets/платье.png
    - assets/мишка.png
    - assets/butterfly.png
    - assets/heart.png
    - assets/png_transparent.png
    - assets/heart2.png
    - assets/heat1.png
    - assets/bij.png
    - assets/гардероб gkfnmt.png
    - assets/гардероб hear.png
    - assets/shopAll.png
    - assets/Гардероб.jpg
    - assets/Гардероб (2).jpg
    - assets/инста.значок.png
    - assets/settingsNew.png
    - assets/logoggogogogogoggogoInsta.png
    - assets/лого.jpg
    - assets/label_sale yellow.png
    - assets/l1c1h3b0e1.png
    - assets/old-grunge-paper-texture-background.jpg
    - assets/Могущество.png
    - assets/Пылкость.png
    - assets/Равновесие.png
    - assets/Тайные желания.png
    - assets/бесплатная.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # starsirius:
  fonts:
    - family: Schyler
      fonts:
        - asset: assets/Lora-VariableFont_wght.ttf
    - family: Nunito
      fonts:
        - asset: assets/Nunito-Black.ttf
    - family: Nunito-Regular
      fonts: 
        - asset: assets/Nunito-Regular.ttf
        
   
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
